##############################################################################
# plugins for markdown
##############################################################################

#   <C-p> Previwe Markdown (only when markdonw file is edting, this config is available)

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_add = '''
    autocmd BufRead,BufNewFile *.md  set filetype=markdown
    let g:vim_markdown_folding_disabled=1
    let g:previm_enable_realtime=1
'''
hook_post_source = '''
    nnoremap <silent> <C-o> :PrevimOpen<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']
