##############################################################################
# Basic plugins
##############################################################################

##### color scheme #####
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
colorscheme iceberg
'''
